### ISSUE TITLE
첫 미니프로젝트 회고

### ISSUE THREAD

**Issue by chohoon901** [BigData23th/MachineLearning#10]
# 4줄 일기
> 이틀간 간단한 데이터 시각화 팀프로젝트를 진행했다. kaggle에서 전 세계 지진 데이터를 받아와서 시각화를 하였다.

> 코랩(colab)에서 파이썬과 matplotlib, folium 등의 라이브러리를 사용하였는데 파이썬을 배운지 얼마 안되서 생각만큼 다룰 수 없었다.

> 학부시절에 파이썬은 쉽다 라는 말만 듣고 공부를 소홀히 한 1년전의 내가 부끄러워 졌다. 파이썬 공부를 더 해야겠다.

> 다음 프로젝트도 파이썬을 기본적으로 활용할 것 같은데 그동안 파이썬 공부를 좀더 하고 여러 예제도 더 풀어봐야겠다.

**Comment by qus0in** [comment]
👍
