### ISSUE TITLE
2023.03.17

### ISSUE THREAD

**Issue by zihvvan** [BigData23th/MachineLearning#11]
# STAR ⭐  

## **Situation (상황)**
> * 오늘 수업에서는 인공지능, 머신러닝, 딥러닝의 정의와 의미를 알아가며 다음주 월요일부터 시작하는 머신러닝을 미리 맛볼 수 있었습니다. 
> * 전날 데이터 시각화 프로젝트를 진행하며 전반적인 구조를 잘 익힐 수 있었습니다. 🔆 

## **Task (과제)**
> * 프로젝트를 진행하면서 지도로 데이터를 표현하는 작업을 진행 중, 데이터의 형식이 올바르지 않아서 난관에 부딪혔습니다. 🙅  

## **Action (행동)**
> * chatgpt를 통해서 문제를 해결하려 했으나 원하는 답변을 얻지 못하였고, 결국 강사님에게 질문을 하며 문제가 되는 데이터 타입의 문제를 "info()" 를 통해 분석하며 해결해 나갔습니다. 🚶‍♂️ 
## **Result (결과)**
> *  apply와 람다함수, astype(float)를 통해 기존의 잘못된 Object 형태의 데이터를 수정하며 데이터 시각화 작업을 해결했습니다. 🕺

**Comment by qus0in** [comment]
👏
