### ISSUE TITLE
2023.03.17.(금) 회고

### ISSUE THREAD

**Issue by Hyunsung1994** [BigData23th/MachineLearning#12]
###### METT+TC로 성찰하겠습니다.

<br/>

### Civil consideration : 강사님께서 추천해주신 프로그래밍 유튜브를 시청하며 스스로 공부할 수 있도록 한다.

<br/>

###### Civil consideration(민간고려요소) : 각종 정책·지원제도 적극 활용

**Comment by qus0in** [comment]
😅
