### ISSUE TITLE
23.03.17 회고

### ISSUE THREAD

**Issue by CHOISEONGGU** [BigData23th/MachineLearning#13]
# STAR ⭐ 
---
> Situation (상황)
3.15-16 데이터처리 후 시각화 프로젝트를 진행했다.
---
> Task (과제)
음원사이트로부터 장르별로 노래 가사들을 정보를 얻어 워드클라우드로 시각화하여 각각의 장르에서 가장 많이 등장하는 단어가 무엇인지 count하여 시각화 하였다.
---
> Action (행동)
* 처음 접했던 동적 크롤링을 공부하고, 음원사이트로부터 xpath를 따와서 코드를 작성하고 데이터를 끌어오는 과정에서 path의 상위 단계를 끌어와 원하지 않았던 데이터가 들어왔었다. googling과 chatGPT를 활용해여 더욱 디테일한 하위 path를 사용하면 된다는 것을 알고 난 후 원하는 데이터를 얻을 수 있었다.
* 가사가 등록되지 않는 노래들에 대해선 str null 을 지정하여 입력하여 주었고, 이 후 데이터 처리하는 과정에서 이를 제거를 해주었다.
---
> Result (결과)
* 같이 진행한 팀원의 결과물은 처음 설계했던 내용으로 장르별 워드클라우드가 나왔지만, 내가 직접 작성한 코드에서는 데이터 처리과정에서 난항을 겪어 결국 장르 전체의 가사들을 가지고 워드클라우드 결과를 만들었다.

* 처음으로 직접 진행해본 데이터 시각화 프로젝트여서 아직 로직적 코드 작성에 부족함을 느꼈다. 주말간 코드 리뷰를 통해서 데이터 수집, 처리 부분에서 보완을 해보고 새로운 데이터로도 한번 해볼 것이다.

* 추가로 공공 data포털에서 제공하는 데이터로도 틈틈히 데이터처리 과정을 연습해보아야겠다.

**Comment by qus0in** [comment]
😮
