### ISSUE TITLE
2023.03.17 회고

### ISSUE THREAD

**Issue by mastgm0817** [BigData23th/MachineLearning#14]
## Keep (유지할 것)
---

프로젝트의 목적과 이유, 명세서를 만드는 과정을 단순히 머리속으로 진행하기 보다는, 문서화하는 습관을 유지 할 것이다.
> 우리가 무엇을 하고 싶은지(주제 선택), 그에 맞는 데이터 수집 방식(공공데이터, Kaggle or Crawling), 데이터 전처리와 적절한
시각화 방법(차트선정)을 선정하고 배포까지 문서화.
---

## Problem (문제점)
---

+ Colab으로 작성했던 Matplotlib 라이브러리가 Streamlit으로 옮겨서 실행을 하니 차트를 그리는데 있어서 한글이 깨짐
> Plotly를 사용하여 해결
+ Colab에서 사용이 가능했던 메소드들이 Streamlit에서는 지원이 하지 않음 
> requirements.txt에 필요한 라이브러리들을 등록하였고, 포멧에 맞게 작성하여 해결
+ UI적인 부분을 조금더 커스터마이징 하기위 HTML-CSS style, Markdown을 사용하려 했으나 적용되지 않고 에러가 발생
> st.markdown(f'<style>{css}</style>', unsafe_allow_html=True) 을 통해 해결
+ 우리 프로젝트의 목적은 짧은 시간이다보니, 여태까지 배운것들을 기본적으로 사용할수있는지를 점검하고, 다양한 차트를 사용해보는것에 목적을 뒀음
---

## Try (시도해 볼 것)
---

+ 디자인 부분 신경 더 써볼 것 ( Streamlit에서 부트스트랩 적용)
+ 이번 프로젝트의 개인적인 1차 목표부분에 있어서는 어느정도 달성하였지만, 보완할 부분도 또한 많이 느꼈다,
> 예를들어, 차트간, 데이터간의 연관성을 보여주는 부분이 부족 -> 차트가 보여주고자하는 결론의 신뢰성에 문제가 제기가 됨
> 이를 뒷받침할 2011 - 2022년까지의 데이터를 보여줄수있는 차트와, 사용자가 지정한 만큼의 연도의 누적 데이터치를 보여줄수있는 차트를 추가해볼생각

+ 코드가 지저분함 -> 중복되고 반복되는 코드부분을 따로 빼서 함수화를 해야겠음.

**Comment by qus0in** [comment]
💯
