### ISSUE TITLE
23.03.17 회고

### ISSUE THREAD

**Issue by JaejinLee1215** [BigData23th/MachineLearning#16]
# 🔆 STAR ⭐ 기법

## Situation (상황) 💮

> 오늘은 python 기초부터 시각화까지 배운 것을 바탕으로 미니프로젝트 진행한 것을 간단하게 리뷰해보았다.
커리큘럼 상 다음 예정인 머신러닝에 대해 배우기 전에 인공지능에 대한 기초적인 개념부터 인공지능 > 머신러닝 > 딥러닝의 비교와 머신러닝 프로세스 과정을 알 수 있었다.
> 

## Task (과제) 📚

> 술 성분 관련 비교를 하려고 맥주, 위스키, 와인 등의 데이터를 국내 데이터포털 사이트를 찾아보았지만 거의 있지 않았고 있어도 소량의 데이터와 품목들만 있어서 api 크롤링을 하고 난 뒤에 좌절하고 주제를 변경하였다.
> '금리, 외환보유액, 환율의 차트 비교' 주제로 첫 미니 프로젝트를 진행하였다. python 언어를 이용하여 numpy, pandas를 기반으로 csv파일을 내가 원하는 데이터로 정제하여 Matplotlib, Seaborn를 사용해 시각화를 하는 workflow로 흘러갔다.
>
> 그 중 데이터를 커스텀 하는 중에 멀티인덱스를 사용하여 시각화를 바로 해야하는 상황이 있었는데 이 과정에서 예전에 다뤄보지 않았던 데이터 구조라 많은 시간이 소요되면서 프로젝트에 진전이 없었다. 또한 시각화를 할 때 멀티인덱스 여서 matplotlib, Seaborn 예제 코드 중 x, y 값을 무엇으로 지정해야하며 어떠한 그래프로 그려야하는지 고민이 되었다.
> 

## Action (행동) 🏃

> 구글링을 기반으로 하고 Chat GPT와 여러 사람에게 질문해본 결과 내가 이해하지 못하는 코드들로 구성되어 있어서 예제 코드들을 참조하고 리스트컴프리헨션을 통해 해결하였다.
시각화 과정에서 Matplotlib, Seaborn을 사용하며 2차원 데이터프레임으로 그려보려 시도했지만 수차례 시도해보고 검색해본 결과 heatmap 등 소수의 그래프들만 그려질 수 있었다는 것을 알게 되었다.
> 

## Result (결과) ✏️

> 처음에 데이터를 충분히 찾아보지 않고 선택해서 필요없는 시간을 소비한 점.
> 금리, 외환보유액, 환율은 이미 경제 관련 이론들을 수학적 계산으로 나온 값들이므로 생각보다 활용하기 어렵다는 점.
> 멀티인덱스 말고 다른 방법도 있을텐데 데이터 정제시 앞만 보고 달리는 말처럼 크게 생각하지 못해 더러운 데이터가 되어 프로젝트진행에 지장을 준 점.
> 
> 첫 프로젝트를 진행하면서 포부가 컸지만 시행착오가 많았고 성과물이 좋지 못해 매우 안타까웠다. 심지어 streamlit 으로 웹페이지 처럼 보여주고 싶었으나 시간과 아직 자질이 부족해 나의 분수를 알게 되었고 다른 사람들의 결과물과 비교해보니 좌절감이 매우 커서 오늘 하루가 우울했다. 다음주 머신러닝을 배우고 3월 말에 미니 프로젝트가 또 있는데 그 때에는 실수를 줄이고 팀원들과 화합하며 잘 진행해봐야겠다.
>

**Comment by qus0in** [comment]
😿
