### ISSUE TITLE
2023/03/17 수업

### ISSUE THREAD

**Issue by JoySoon** [BigData23th/MachineLearning#2]
# 네줄일기

- 사실 : 주어진 기한에 맞춰 시각화 과제를 완료
- 발견 : 제출한 과제에서 보완할 점이 많다는 점을 발견함
- 학습 : 과제 발표 이후 머신러닝 이론 수업을 함
- 선언 : 앞으로도 많은 프로젝트를 할텐데 기본을 잘 다져놔야 할 것 같다

**Comment by qus0in** [comment]
👍
