### ISSUE TITLE
회고

### ISSUE THREAD

**Issue by baejinu** [BigData23th/MachineLearning#25]
# 사실
* 머신러닝 선형회귀, 로지스틱회귀를 배웠다.

# 발견
* 생소하다, 그래서 복잡하다.

# 학습
* 데이터 처리에 대해서 배웠다. 선형회귀는 직선형, 로지스틱회귀는 수렴형으로 배웠다.

# 선언
* 복습해봐야지

**Comment by qus0in** [comment]
👍
