### ISSUE TITLE
2023_03_17_회고

### ISSUE THREAD

**Issue by cc5547** [BigData23th/MachineLearning#3]
---
> ## 상황(Situation) 
> * ### 23_03_15 ~ 23_03_16동안 데이터 시각화를 활용하는 미니 프로젝트를 진행하였습니다.
---
> ## 과제(Task)
> * ### 주제를 정의 후 단기간 시간인 만큼 시간 단위로 일정을 수립하고 프로젝트를 빠르게 진행할 수 있는 대안을 모색했습니다.
---
> ## 행동(Action)
> * ### 먼저 팀원과 면담하여 문제를 파악하고 일정을 수립했습니다. 2인이 팀이었기에 시각화에 필요한 그래프 부분의 모듈을 부탁하여 팀원은 그래프 관련 모듈을 개발하고 저는 전체적인 자료 흐름을 기반으로 알고리즘과 로직을 개발하고 통합하였습니다.
---
> ## 결과(Result)
> * ### 프로젝트가 예정된 일정 내에 완료되었습니다. 또한, 팀 내 협업과 밝은 분위기의 커뮤니케이션으로 원활하게 진행하였습니다. 이 경험을 통해 팀 내 협업과 일정 관리의 중요성을 다시금 깨닫고, 기간 내에 할 수 없을 거라 생각했지만 좋은 협업 진행으로 빠르게 결과를 도출할 수 있다는 걸 깨달았습니다.
---

**Comment by qus0in** [comment]
💯
