### ISSUE TITLE
23.03.21 회고

### ISSUE THREAD

**Issue by CHOISEONGGU** [BigData23th/MachineLearning#42]
# 4줄 일기
---
> 사실 Fact
머신러닝 ch2 model - KNN, Naive bayes에 대해서 알게되었다.
> 발견 Discovery
지난번 데이터 시각화 프로젝트 때, 진행했던 word cloud 와 naive bayes와 비슷한 내용이다는 것을 알게 되었다.
조금은 반가웠다.
> 배운점 Learning
새로운 전처리 과정들을 배웠다. 머신러닝을 배운건지 전처리 과정을 배운건지 모르겠다.
> 선언 Declaration
전처리 과정에 대한 많은 방법들의 정리가 필요하다.

**Comment by qus0in** [comment]
👀
