### ISSUE TITLE
03-17 회고

### ISSUE THREAD

**Issue by Myun9hyun** [BigData23th/MachineLearning#7]
# 03-17 회고
* 오늘의 회고는 STAR기법으로 작성하겠습니다.
---
* Situation(상황)
> * 오늘은 2일간 미니프로젝트를 진행했고, 그 미니 프로젝트에 결과물에 대한 발표가 있었습니다.
* Task(과제)
> * 미니 프로젝트를 진행하던 중 데이터를 추출하는 것에 어려움을 느꼈습니다.
* Action(행동)
> * 미니프로젝트간 데이터 추출은 타 조원이 진행하기로 했고 저는 streamlit에 구현하는 역할을 맡았습니다.
* Result(결과)
> * 다른 조원들이 열심히 노력한 결과 좋은 데이터가 많이 나오고 그래프로 시각화 되어 좋은 득표를 얻었습니다.
> * 덕분에 강사님에게 맛있는 쿠키도 받게 되었습니다.
> * 주말간 데이터 추출에 대한 공부를 더 해야할 필요성을 느꼈습니다.

**Comment by qus0in** [comment]
🍪
