### ISSUE TITLE
0327 회고

### ISSUE THREAD

**Issue by chohoon901** [BigData23th/MachineLearning#79]
## 네줄일기
* 오늘은 아침에 kmeans clusturing과 pca를 복습한뒤 본격적인 머신러닝 프로젝트를 시작하였다. 
* 주말동안 각자 데이터를 전처리 해온것 중 가장 전처리가 잘 된것을 바탕으로 추가 전처리를 진행하고 모델링을 진행하였다. 
* 전처리 하는 동안에는 전처리 하느라 세상 오래 걸려서 머리가 깨지는줄 알았는데 모델링 단계로 넘어가니 모델링 돌리는데 한세월 이었다. 
* 집에가서 집 컴퓨터로도 모델링을 돌려야겠다.

**Comment by qus0in** [comment]
👍
