### ISSUE TITLE
2023/03/27 미니프로젝트 회고

### ISSUE THREAD

**Issue by JoySoon** [BigData23th/MachineLearning#81]
# STAR

## Situation (상황)

- 전처리를 주말에 완료한 상태였고 모델링도 각자 맞은 바에 따라 완료하였으며 본격적으로 시각화 작업에 들어갔습니다. 저는 XGBoost 모델링을 사용하였으며 streamlit으로 작업하는 시각화 작업을 담당하였습니다.

## Task (과제)

- 머신러닝을 활용하여 주제로 정한 데이터를 전처리하고 다양한 방법으로 모델링을 한다. 그리고 이렇게 모델링한 데이터를 어떻게 활용할 지 대해 고민하고 이를 실행해본다.

## Action (행동)

- 인터넷과 ChatGPT를 참고하여 streamlit으로 시각화 작업을 진행하였습니다.

## Result (결과)

- 일단 대략 전체 과정에서 80%정도 마무리했다고 확신합니다. 내일 전처리 보강과 오류 발견 및 PPT 제작, 발표 준비로 잘하면 내일 미니프로젝트를 마무리 할 수 있다고 봅니다.

**Comment by qus0in** [comment]
👍
