### ISSUE TITLE
0328 회고

### ISSUE THREAD

**Issue by chohoon901** [BigData23th/MachineLearning#83]
## 4줄일기
* 오늘은 어제와 다르게 전처리 할 것들이 생겼다. 우선 평단가를 넣지 않기로 했고, 2개월간의 데이터가 아닌 반년간의 데이터를 사용하면서 금리 변화를 반년간에 실제 금리 변화량으로 맟췄다. 이때 금리 변화 조건이 여러개가 되면서 원래 사용하던 람다식에서 인덱싱을 활용하여 금리값을 바꾸는 걸로 방법을 바꿨다. 
* 그 후 랜덤포레스트가 결정트리의 한 갈래라는걸 듣고 랜덤포레스트를 사용해야하는 것이라고 생각했지만 아니어서 급하게 결정트리 회귀로 방향을 틀었다. 
* 이때 random_state값을 1065로 정했다. 반복문을 여러번 돌려본 값 중 이 값이 rmse가 가장 낮았다. 
* 평단가를 빼고 모델링을 돌렸더니 rmse값이 너무 높게 나왔다. 하이퍼 파라미터 조정이 더 필요해 보였다. ppt를 하면서 좀더 건드려봐야겠다.

**Comment by qus0in** [comment]
👍
