### ISSUE TITLE
2023/03/28  프로젝트 회고

### ISSUE THREAD

**Issue by JoySoon** [BigData23th/MachineLearning#85]
# STAR

## Situation (상황)

- 어제 진행된 프로젝트 결과물의 완성도를 높히기 위해 팀원 모두 분주히 움직였습니다.

## Task (과제)

- 내일 점심까지 프로젝트 결과물을 완성하고 ppt발표를 준비한다.

## Action (행동)

- ChatGPT와 강사님의 도움으로 streamlit을 통해 제가 맡은 XGBoost 모델링 시각화 작업을 완성하였습니다.

## Result (결과)

- 내일 점심까지 프로젝트 결과물이 완성될 것이라고 확신합니다. 혹시 발생할 수 있는 프로젝트에 발생할 수 있는 약간의 오류만 잡아내면 완성도 높은 결과물을 선보일 수 있을 것입니다.

**Comment by qus0in** [comment]
👍
