### ISSUE TITLE
2023/03/29 프로젝트 회고

### ISSUE THREAD

**Issue by JoySoon** [BigData23th/MachineLearning#86]
# STAR

## Situation (상황)

- 오늘 오후 12시 기점으로 프로젝트를 완성했습니다.

## Task (과제)

- 모델링에 RMSE같은 신뢰도 검사를 실행해준다.
- 모델을 한꺼번에 확인할 수 있는 화면이 있으면 좋겠다.
- 이 모든 경험은 자소서 거리가 될 수 있다.
- kaggle이랑 dacon에 조금씩 도전해보자

## Action (행동)

- 추가할 것이 있으면 추가하였고 몇 번의 시연회로 버그가 있는 지를 확인하였습니다. 확인한 다음, ppt를 제작하고 발표 준비를 하였습니다.

## Result (결과)

- 발표는 무난히 마쳤습니다. 지금 돌아보면 부족한 점이 많지만 좋은 경험이었습니다. 앞으로도 분발해야겠습니다.

**Comment by qus0in** [comment]
👍
