### ISSUE TITLE
3월 29일 22일차 회고

### ISSUE THREAD

**Issue by Yeaaaaaaah** [BigData23th/MachineLearning#89]
네줄일기
사실 : Accuracy score를 올리기 위해 노력했다
발견 : Accuracy score 향상을 시키기 위해 표준화 스케일링을 진행해보고, 
Grid Search, Random Search, OPTUNA같은 툴을 이용해 최적의 파라미터를 탐색하고, 얻은 파라미터를 사용해 Voting을 진행해보고, random state 값 조절을 조절하고, Feature mportance , permutation importance 값을 활용해 독립변수를 제거,통합하고 인코딩해봤다.
학습 : 정확도 1~2%를 올리는 것이 정말 힘들다는 것을 알 수 있었습니다. 그리고 정확도 뿐만 아니라 ROC AUC Score, k-fold 등의 검증 방법을 통해 다양하게 모델의 성능을 평가하고 향상시켜 나가야 한다는 것을 알게되었습니다.또, 나와는 다른 방식으로 진행한 팀원의 코드를 보면서, 같은 결과를 내도 다양한 방식으로 코딩할 수 있다는 것과 타인의 코드를 이해하고 수정하려면 공부를 많이 해야한다는 것을 느꼈습니다. 
선언 : 이번에 머신러닝에 대해 배운 것을 정리하고 공부해서 다음엔 더 나은 결과를 낼 수 있도록 해야겠습니다.

**Comment by qus0in** [comment]
👍
